"""1 миграция

Revision ID: b3f935a1a206
Revises: 
Create Date: 2026-04-12 04:57:12.745884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f935a1a206'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('faculty', sa.Enum('AVTF', 'FPMI', 'FLA', 'REF', 'FTF', name='faculty'), nullable=False),
    sa.Column('course', sa.Enum('Theor_Mechanics', 'Mat_Analysis', 'Informatics', 'History', 'Psychology', 'Physics', name='course'), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
